### PR TITLE
add num_cpu_cores_per_socket to vmware deployment

### PR DESCRIPTION
**Pull request by gauthiersiri**
add num_cpu_cores_per_socket  to better use hyperthreading

### CODE REVIEW

**Comment by mallmen** [comment]
can you do "default(1)" instead?  since that should be the case if you don't specify num_cpu_cores_per_socket at all

**Comment by gauthiersiri** [comment]
Done! i've just defaulted cores_per_socket to 1

**Comment by mallmen** [comment]
Hey, sorry for making multiple asks here.  First, this PR needs to be rebased against PR#100 that I just merged.  Second, in the spirit of the other PR, can we make the same similar change?  Add something to the new `vm_mods` section for `master_cores_per_socket` and `worker_cores_per_socket`, and the set the cores at vm creation using `default(omit)` if not specified?

**Comment by gauthiersiri** [comment]
Done! you're right it will be easier this way!

**Pull request merged**
