### PR TITLE
add maxdistance to chrony.conf

### PR DESCRIPTION
**Pull request by tuxpeople**
For compliance with Windows AD servers serving as a NTP server, as described in https://access.redhat.com/solutions/4652771

### CODE REVIEW

**Comment by mallmen** [comment]
Hi @tuxpeople, I would like to make your suggested change an option as opposed to a change for everyone.  Could you make the change to the chrony.conf.j2 template conditional on defining a maxdistance value in group_vars/all.yml?  Add a ntp.maxdistance, and then the template will set the value if it exists.

**Comment by ddreggors** [comment]
This PR is now 2 years old (as is the last comment to add `ntp.maxdistance`). We should be aware that we have now added support for multiple distinct cluster vars under the clusters folder. How this applies here is that we would not just rely on `group_vars/all.yml` but would now add this key to individual cluster files. So in addition to adding that key (and sane default value) to  `group_vars/all.yml` we would also add to the example cluster file (`clusters/ocp-example.yaml`)

**Comment by ddreggors** [comment]
I mis-read the request, yes we should check for the key to exist and only set it it does... no matter where it is set. This can be added via extra vars on command line (`-e ntp.maxdistance`), in `group_vars/all.yml` or in cluster specific files `clusters/ocp-example.yaml` in this manner

**Comment by ddreggors** [comment]
We should close this PR as there is no response in 2 years and is now replaced by #97

**Comment by mallmen** [comment]
clsoing in lieu of PR#97

**Pull request closed without merging**
