### PR TITLE
fix worker length

### PR DESCRIPTION
**Pull request by gauthiersiri**
add | length when checking workers CSRs

### CODE REVIEW

**Comment by gauthiersiri** [comment]
Hi, any chance to have this PR review and eventually merged? :)

**Comment by gauthiersiri** [comment]
@ddreggors Any chances to see this PR merged :)

**Comment by dadreggors** [comment]
Sadly it seems I do not have permissions to merge any longer in this repo as I see no merge button now :-(

**Comment by dadreggors** [comment]
@mallmen can you please review and merge?

**Pull request merged**
