### PR TITLE
Proxy for installation time

### PR DESCRIPTION
**Pull request by fsbano**
Proxy for installation time

### CODE REVIEW

**Comment by fsbano** [comment]
Proxy for installation time

**Comment by vchintal** [comment]
This is awesome please give me a day or two to test it and merge.

**Comment by vchintal** [comment]
Hi @fsbano, I could not successfully test your pull request. I assume you ran at least one test with the changes you committed? If yes, could you please attach the `install-config.yml.orig` in the `install-dir`? The additionalTrustBundle in the `group_vars/all.yml` could not be successfully applied via the template. The resulting file, after the template application shows wrongly formatted `additionalTrustBundle` entry in `install-config.yml`

**Comment by fsbano** [comment]
> Hi @fsbano, I could not successfully test your pull request. I assume you ran at least one test with the changes you committed? If yes, could you please attach the `install-config.yml.orig` in the `install-dir`? The additionalTrustBundle in the `group_vars/all.yml` could not be successfully applied via the template. The resulting file, after the template application shows wrongly formatted `additionalTrustBundle` entry in `install-config.yml`

@vchintal ,

Can you send me your final version ?

* Please use self-assigned certificate (fake)

Regards,
Fábio Sbano

**Comment by vchintal** [comment]
@fsbano Sorry, what do you mean by the final version ? The install-config.yml.orig that gets left over in install-dir after the file is picked and processed ?

**Comment by fsbano** [comment]
I will make some improvements

**Pull request closed without merging**
